name: Go Test 

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Run Test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
      id: Go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Run tests
      run: go test ./...
