name: Go Test & Codecov . 

on: 
  push:
    branches: [main] 
  pull_request:
    branches: [main] 


jobs:
  build:
    name: Run tests and upload to codecov.io
    runs-on: ubuntu-latest

    steps:
    - name: Set up go 
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
      id: Go

    - name: Check out code into the Go module directory 
      uses: actions/checkout@v3

    - name: Run tests with coverage 
      run: go test -coverprofile=coverage.txt ./...

    - name:  Upload coverage reports to codecov.io
      uses: codecov/codecov-action@v3
      with: 
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt
        flags: unit-tests 
        name : codecov-umbrella 
        fail_ci_if_error: true 
     
